### ISSUE TITLE
LoadContent expects the root child to have content?

### ISSUE THREAD

**Issue by Pryme8** [playcanvas/earthatile#5]
When I took a peek at the code and started trying to work my way through it I noticed that the root.json.children does not have any content?

![image](https://github.com/playcanvas/earthatile/assets/1538857/d51e7260-099a-4459-9a67-b9da4c06f5f9)

So it seems when running ``` expandNode(json.root) ``` once the method does the promise.all on the roots children the code goes nowhere due to the ``` if (node.content) { ``` evaluation in the loadContent function.

From looking at the data structure it seems the roots.children.children have the content?

Is there a step I am missing?

**Comment by willeastcott** [comment]
Oh hi @Pryme8 - I remember you from the forums. 👋 

So, initially, in the start function, `expandNode` is called, but looking at the code, I think it's sufficient to simply add the root to `this.expandedNodes`. But it should be the same outcome.

The initial sequence is something like:

1. Load root tileset JSON.
2. Expand the root node.
3. This essentially adds the root to `this.expandedNodes`.
4. On the next call to `update` all children (there's 1) are iterated. If it's in range (which it is), it's expanded.
5. Go to 4 (and continue down the hierarchy).

Frankly, it's written for simplicity, not efficiency. 😉

**Comment by Pryme8** [comment]
Its been a while surprised you remember me ;)!
After looking at it, I realized its the update method kind of handles everything after the node.children is set to json.root.

So your answer is spot on, thank you!

Looks like it does that cycle twice before it gets access to the glbs, but if that works then ill run with it.

Going to test this now, but just after your input it seems that is what's happening for sure.

Appreciate the quick response <3.
